# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hebi_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Arm/J1_base
    - Arm/J2_shoulder
    - Arm/J3_elbow
    - Arm/J4_wrist1
    - Arm/J5_wrist2
    - end_effector/input_l_finger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: hebi_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Arm/J1_base
      - Arm/J2_shoulder
      - Arm/J3_elbow
      - Arm/J4_wrist1
      - Arm/J5_wrist2
hand_controller:
  type: GripperCommand
  joints:
    end_effector/input_l_finger
  gains:
    end_effector/input_l_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1